version: '3.8'

services:
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=suntina
    ports:
      - '5432:5432'
    user: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  # app:
  #   container_name: app
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DB_URI=${DB_URI}
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - DB_HOST=${DB_HOST}
  #       - DB_PORT=${DB_PORT}
  #     - DB_NAME=${DB_NAME}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     db:
  #       condition: service_healthy
       
